module.exports = {
  "moduleData": {
    "id": 17679,
    "name": "hook",
    "cover": "https://img.alicdn.com/tfs/TB1mkjeqlr0gK0jSZFnXXbRRXXa-1404-1292.png",
  },
  "code": {
    "panelDisplay": [
      {
        "panelName": "index.jsx",
        "panelValue": '<?xml version="1.0" encoding="utf-8"?><Flex  flexDirection="row" alignItems="flexStart"><Flex  marginTop="1" position="relative" background="#ffffff" flexDirection="column" alignItems="flexStart"><Image  width="171" height="161" position="absolute" top="1" src="https://img.alicdn.com/tfs/TB1hIP.z1H2gK0jSZFEXXcqMpXa-684-644.png"/><Image  width="171" height="162" marginTop="1" position="relative" src="https://img.alicdn.com/tfs/TB1MroXz5_1gK0jSZFqXXcpaXXa-684-648.png"/><Flex  position="relative" background="#ffffff" flexDirection="row" justifyContent="center" alignItems="flexStart"><Text  marginTop="9" textColor="#333333" textSize="15" ellipsize="end" text="拥有超多功能的40平米简约小公寓了解一下"/></Flex><Flex  paddingRight="5" paddingLeft="5" position="absolute" top="154" left="9" background="#ffb902" borderRadius="3" flexDirection="row" alignItems="center"><Text  textColor="#ffffff" textSize="10" text="整屋"/></Flex><Flex  position="relative" background="#ffffff" borderLeftBottomRadius="6" borderRightBottomRadius="6" flexDirection="row" justifyContent="center" alignItems="center"><Flex  marginTop="1" marginRight="20" flexDirection="row" alignItems="center"><Flex  marginRight="3" position="relative" flexDirection="row" justifyContent="center" alignItems="flexStart"><Image  width="15" height="15" position="absolute" src="https://img.alicdn.com/tfs/TB1sWY9z.H1gK0jSZSyXXXtlpXa-60-58.png"/><Image  width="15" height="15" position="relative" src="https://img.alicdn.com/tfs/TB1bWr.z.T1gK0jSZFhXXaAtVXa-60-58.png"/></Flex><Text  textColor="#666666" textSize="12" ellipsize="end" text="花花设计工作…"/></Flex><Flex  marginTop="1" flexDirection="row" alignItems="center"><Image  width="12" height="11" marginTop="1" marginRight="2" src="https://img.alicdn.com/tfs/TB11jn9z.T1gK0jSZFrXXcNCXXa-46-44.png"/><Text  textColor="#999999" textSize="11" text="168"/></Flex></Flex></Flex></Flex>',
        "panelType": "js"
      },
      {
        "panelName": "style.js",
        "panelValue": "export default {\n  box: {\n    display: 'flex',\n    alignItems: 'flex-start',\n    flexDirection: 'column',\n    borderRadius: '3.20vw',\n    backgroundColor: '#ffffff',\n    width: '93.60vw',\n    height: '86.13vw'\n  },\n  bd: { width: '93.60vw', height: '52.53vw' },\n  main: {\n    marginTop: '4.00vw',\n    marginLeft: '3.20vw',\n    width: '42.67vw',\n    maxWidth: '88.80vw',\n    height: '4.80vw',\n    overflow: 'hidden',\n    textOverflow: 'ellipsis',\n    lineHeight: '4.80vw',\n    whiteSpace: 'nowrap',\n    color: '#333333',\n    fontSize: '4.27vw',\n    fontWeight: 500\n  },\n  submain: {\n    marginTop: '2.13vw',\n    marginLeft: '3.20vw',\n    width: '90.13vw',\n    height: '10.67vw',\n    overflow: 'hidden',\n    textOverflow: 'ellipsis',\n    lineHeight: '5.33vw',\n    color: '#888888',\n    fontSize: '3.47vw',\n    fontWeight: 300\n  },\n  ft: {\n    boxSizing: 'border-box',\n    display: 'flex',\n    flexDirection: 'row',\n    justifyContent: 'space-between',\n    marginTop: '3.20vw',\n    paddingRight: '3.07vw',\n    paddingLeft: '3.20vw',\n    width: '93.60vw'\n  },\n  outer: { display: 'flex', alignItems: 'center', flexDirection: 'row', height: '4.80vw' },\n  wrap: {\n    display: 'flex',\n    position: 'relative',\n    alignItems: 'flex-start',\n    flexDirection: 'row',\n    justifyContent: 'flex-end',\n    width: '4.80vw',\n    height: '4.80vw'\n  },\n  icon: { position: 'absolute', top: '0.00vw', left: '0.00vw', width: '4.80vw', height: '4.80vw', overflow: 'hidden' },\n  icon_2: { position: 'relative', marginTop: '2.93vw', width: '1.87vw', height: '1.87vw' },\n  beautifulClothesFashion: {\n    marginLeft: '0.80vw',\n    width: '12.80vw',\n    height: '3.73vw',\n    lineHeight: '3.73vw',\n    whiteSpace: 'nowrap',\n    color: '#666666',\n    fontSize: '3.20vw',\n    fontWeight: 300\n  },\n  tagWrap: {\n    boxSizing: 'border-box',\n    display: 'flex',\n    alignItems: 'flex-start',\n    flexDirection: 'row',\n    marginLeft: '0.80vw',\n    borderRadius: '0.80vw',\n    backgroundColor: 'rgba(253,234,238,0.90)',\n    paddingRight: '1.20vw',\n    paddingLeft: '1.07vw',\n    height: '3.73vw'\n  },\n  tag: {\n    marginTop: '0.27vw',\n    width: '10.67vw',\n    height: '3.20vw',\n    lineHeight: '3.20vw',\n    whiteSpace: 'nowrap',\n    color: '#ff2c54',\n    fontSize: '2.67vw',\n    fontWeight: 400\n  },\n  block: { display: 'flex', flexDirection: 'row' },\n  icon_3: { marginTop: '1.47vw', width: '3.47vw', height: '2.67vw' },\n  num: {\n    marginTop: '1.20vw',\n    marginLeft: '0.80vw',\n    width: '6.40vw',\n    height: '3.20vw',\n    lineHeight: '3.20vw',\n    whiteSpace: 'nowrap',\n    color: '#999999',\n    fontSize: '2.67vw',\n    fontWeight: 400\n  }\n};\n",
        "panelType": "js"
      }
    ],
    "noTemplate": true
  }
};
